import { TideLocation } from "../types/Tide";

//釣り場所データ
export const tideLocation: TideLocation[] = [
    {
        prefecture: "和歌山県",
        prefectureCode: 30,
        harborCode: "11",
        nameJp: "和歌山市",
        latitude: 34.226,
        longitude: 135.167,
        mapImage: "/maps/wakayama.png",
    },
    {
        prefecture: "和歌山県",
        prefectureCode: 30,
        harborCode: "10",
        nameJp: "海南",
        latitude: 34.150,
        longitude: 135.200,
        mapImage: "/maps/kainan.png",
    },
    {
        prefecture: "和歌山県",
        prefectureCode: 30,
        harborCode: "9",
        nameJp: "下津",
        latitude: 34.083,
        longitude: 135.100,
        mapImage: "/maps/shimotu.png",
    },
    {
        prefecture: "和歌山県",
        prefectureCode: 30,
        harborCode: "8",
        nameJp: "由良",
        latitude: 33.983,
        longitude: 135.133,
        mapImage: "/maps/yura.png",
    },
    {
        prefecture: "和歌山県",
        prefectureCode: 30,
        harborCode: "13",
        nameJp: "白浜",
        latitude: 33.733,
        longitude: 135.383,
        mapImage: "/maps/tanabe.png",
    },
    {
        prefecture: "和歌山県",
        prefectureCode: 30,
        harborCode: "3",
        nameJp: "串本",
        latitude: 33.28,
        longitude: 135.47,
        mapImage: "/maps/kushimoto.png",
    },
    {
        prefecture: "大阪府",
        prefectureCode: 27,
        harborCode: "6",
        nameJp: "大阪市",
        latitude: 34.39,
        longitude: 135.26,
        mapImage: "/maps/osaka.png",
    },
    {
        prefecture: "大阪府",
        prefectureCode: 27,
        harborCode: "5",
        nameJp: "堺",
        latitude: 34.35,
        longitude: 135.28,
        mapImage: "/maps/sakai.png",
    },
    {
        prefecture: "大阪府",
        prefectureCode: 27,
        harborCode: "4",
        nameJp: "泉大津",
        latitude: 34.3,
        longitude: 135.24,
        mapImage: "/maps/izumiotu.png",
    },
    {
        prefecture: "大阪府",
        prefectureCode: 27,
        harborCode: "3",
        nameJp: "岸和田",
        latitude: 34.28,
        longitude: 135.22,
        mapImage: "/maps/kisiwada.png",
    },
    {
        prefecture: "大阪府",
        prefectureCode: 27,
        harborCode: "2",
        nameJp: "淡輪(Tannowa)",
        latitude: 34.2,
        longitude: 135.11,
        mapImage: "/maps/tannowa.png",
    },
    {
        prefecture: "大阪府",
        prefectureCode: 27,
        harborCode: "1",
        nameJp: "深日(Huke)",
        latitude: 34.19,
        longitude: 135.08,
        mapImage: "/maps/huke.png",
    },
];
